[project]
name = "ucp-sdk" # Use a hyphen here
version = "0.1.0"
dependencies = ["pydantic>=2.0.0"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]  # This tells Python: "The ucp_sdk folder is inside src"